### ISSUE TITLE
大佬有没有可能集成各大手机厂商的系统级推送了。

### ISSUE THREAD

**Issue by graytoowolf** [yafoo/pushme#1]
系统级推送应该方便很多吧。软件不怕被杀了

**Comment by yafoo** [comment]
应该是不太可能，系统级推送一个是要求企业资质，另外就是都有严格的限制，甚至是内容审查。

我自己测试vivo安卓10系统，给够权限，后台服务能运行几天。最新的vivo安卓13系统，夜里手机休眠后，服务会被杀掉。
白天的话，倒没啥问题。
