### ISSUE TITLE
多个推送通道

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme#10]
在实际使用中，根据重要性有对不同类型的消息做不同级别的通知需求，比如：
1. 服务器状态等消息，重要级别，手机开启声音 + 震动通知（自主设置）
2. 一般消息，一般级别，震动通知
3. 其余资讯类，比如新闻快讯，最低级别，无感通知，只在通知栏显示

以前通过微信公众号或者TG频道的方式通知，不同类别的通知用不同的频道推送，在App内就能分开设置通知。

但是现在换到PushMe，所有消息都通过一个通知通道推送，所以每隔几分钟来一条快讯都响，不响又不行，会错过重要信息，手机一天到晚没停过。

希望PushMe客户端可以预留多3-5个通知通道，然后可以在接口指定用哪个通道通知，不指定则使用默认的“MainChannel”
![125b74b64858d1d6124fb5e7b05adfe](https://github.com/yafoo/pushme/assets/8676741/d6c3788a-5e83-463b-a2d3-ded998f8d76e)

这样子就能做到不同类型的消息分开通知

**Comment by yafoo** [comment]
好的，我想想怎么解决

**Comment by yafoo** [comment]
新版本已经发布，支持自定义消息通道

**Comment by liesauer** [comment]
👌今晚测试下
