### ISSUE TITLE
一个小bug，双击消息详情页面的返回按钮会导致整个app页面白屏

### ISSUE THREAD

**Issue by isemikage** [yafoo/pushme#11]
![image](https://github.com/yafoo/pushme/assets/31739879/9a2467b4-ed51-4f91-a3d6-a1fa2c29dd34)

#### 系统: 荣耀的MagicOS 7.0（Android 12）

**Comment by yafoo** [comment]
好的，我看看修复一下

**Comment by yafoo** [comment]
bug已修复，你下载最新版试试
