### ISSUE TITLE
添加代理

### ISSUE THREAD

**Issue by Mczye** [yafoo/pushme#13]
国内网络无法直接使用，需要开代理，但安卓机上不喜欢装代理软件，可不可以设置个代理接口，自行配置，方便获取更新

**Comment by yafoo** [comment]
代理，我后面看看加上。

目前push_key获取动作，是连接的官网。消息服务器和消息通知是用的国内服务器。理论上你获取push_key后，不用开代理的。
你测试下，看能收到消息不？

官网消息发送接口，后面我看看部署一个国内的备用接口。

**Comment by yafoo** [comment]
> 国内网络无法直接使用，需要开代理，但安卓机上不喜欢装代理软件，可不可以设置个代理接口，自行配置，方便获取更新

最新版已内置备用接口，现在国内访问应该没啥问题了，你下载试试。
