### ISSUE TITLE
push_key获取失败

### ISSUE THREAD

**Issue by iamhrm** [yafoo/pushme#15]
pushme v2.3.0,手机是魅蓝note3

**Comment by yafoo** [comment]
不开代理的情况下，官网能打开不？

**Comment by iamhrm** [comment]
能打开



在 2024-05-06 09:49:07，"雨思" ***@***.***> 写道：

不开代理的情况下，官网能打开不？

**Comment by yafoo** [comment]
你加下我wx：zhyaphoo，调试一下吧，看看请求发过来没

**Comment by xiaoyaoyisheng** [comment]
push_key获取失败 同样的问题，手机是荣耀50

**Comment by xiaoyaoyisheng** [comment]
push_key获取失败 同样的问题，手机是荣耀50，系统是Magic OS 8

**Comment by yafoo** [comment]
> push_key获取失败 同样的问题，手机是荣耀50，系统是Magic OS 8

https://push.i-i.me/app.apk
下载安装一下这个调试版本，获取push_key，看看提示的什么信息

**Comment by yafoo** [comment]
> 提示这个 java.net.SocketException: Connection reset

服务器端做了一点小修改，你再获取push_key试一下

**Comment by xiaoyaoyisheng** [comment]
使用正常版本，，已基本正常了，经多次获取后，可以获取到push_key

**Comment by yafoo** [comment]
> 使用正常版本，，已基本正常了，经多次获取后，可以获取到push_key

额，这样不好判断是网络问题还是服务器端问题。设置里有个获取temp_key的项，你获取后更新几次，帮忙测试下成功率多高？

**Comment by bingege2** [comment]
![5a7f473bf16f268edc483ce1873b7df](https://github.com/user-attachments/assets/fb755411-1ce1-4d35-be7d-ea37701bb622)
![9488d97dffe8b1671ca08caa2771dd9](https://github.com/user-attachments/assets/f0a6709f-60f4-4108-aff6-5a71a13e9746)
获取失败 麻烦帮忙看一下
