### ISSUE TITLE
无法后台通知

### ISSUE THREAD

**Issue by idiomer** [yafoo/pushme#16]
小米12 
MIUI 14.0.7 
ANdroid 13

已经给了所有通知权限（包括channel），省电无限制，多任务界面锁住，自启动，其他权限默认

能正常获取和更换push key，前台能接收到通知，但后台就完全不行。（自建服务器也是一样前台可以后台不行）

**Comment by yafoo** [comment]
嗯，之前是可以后台接收通知的，最近我也发现后台好像不行了，我调试调试看咋回事

**Comment by yafoo** [comment]
嗯，之前是可以后台接收通知的，最近我也发现后台好像不行了，我调试调试看咋回事

**Comment by yafoo** [comment]
试了下，我的确实也不能后台接收通知了，但是看不到错误日志。我用开发板调试，没有问题，后台是可以的。然后我卸载开发版，重新安装正式版，发现又可以后台接收通知了。现在还分析不出来原因啊，我再观察观察。

你要不卸载重装试试？我装的是32位版的，另外卸载会造成push_key丢失，只能获取新的push_key.
