### ISSUE TITLE
消息数量过多以后软件打开加载缓慢

### ISSUE THREAD

**Issue by MUskby** [yafoo/pushme#18]
建议增加历史消息定期清理功能，清理掉历史消息，提升软件性能

**Comment by yafoo** [comment]
你的现在有多少条消息？在设置里可以一键清理所有消息。
![微信图片_20240828094123](https://github.com/user-attachments/assets/9a058f9a-0776-4632-ae3c-2b0e2822e74c)
首页默认显示10条消息，一般不会卡顿，你说是首页显示消息过多吗？

**Comment by MUskby** [comment]
现在大概是这么个情况https://github.com/user-attachments/assets/1fc3770b-b426-44a6-9c42-e4cd45f3baff

点开会这样空白一会儿，感觉软件启动很慢，能追踪到问题原因么？

**Comment by MUskby** [comment]
就是每次清理了后台以后重新加载就会很慢，刚开始以为是消息太多了，今天复现的时候发现，不是这么回事儿，只要清了后台再进软件就会很慢

**Comment by yafoo** [comment]
你手机打开PushMe官网慢不慢？

**Comment by yafoo** [comment]
启动时会访问官网接口，这个可能会造成首屏显示慢，之前优化过几次，后来尴尬的发现并没有优化成功，下一版会再优化一下，最近一直比较忙，所以这是一直拖着，估计还得再等些天。

**Comment by MUskby** [comment]
刚特意试了下官网，几乎秒开
没关系，现在是只要能看就还行，不着急

**Comment by yafoo** [comment]
> 刚特意试了下官网，几乎秒开 没关系，现在是只要能看就还行，不着急

官网秒开的话，就不好说了。整个app没多少东西，除了接口可能拖慢速度，别的都不会那么慢啊

**Comment by MUskby** [comment]
老大，清除所有数据打开软件会出现这个![Screenshot_2024-09-01-11-30-05-201_com.android.pushme.jpg](https://github.com/user-attachments/assets/3b5147a7-04a7-4bdc-aa74-fb43bfd56a37)

有影响么？😂

**Comment by MUskby** [comment]
老大，清除所有数据打开软件会出现这个![Screenshot_2024-09-01-11-30-05-201_com.android.pushme.jpg](https://github.com/user-attachments/assets/3b5147a7-04a7-4bdc-aa74-fb43bfd56a37)

有影响么？😂

**Comment by yafoo** [comment]
只要能安装上就行，没影响的。介意的话，可以下载64位版本的。
安卓14不支持32位的应用了，不过国内手机一般做了兼容，可以安装正常使用，像小米手机就是弹了个提示。
我就是故意用的32位的。

**Comment by MUskby** [comment]
okok

**Comment by yafoo** [comment]
你的不是首屏打开慢嘛，你在releases里下载64位的安装试试

**Comment by MUskby** [comment]
感谢老大，64位的目前没问题，秒开，我再试试

**Comment by yafoo** [comment]
好的，再观察观察
