### ISSUE TITLE
期望增加推送文本内容中文全局搜索

### ISSUE THREAD

**Issue by laurenafolk** [yafoo/pushme#19]
有时候想按照推送内容关键字搜索，希望增加一个这个功能，改进一下搜索栏，感谢

**Comment by yafoo** [comment]
好的，有时间改进一下

**Comment by yafoo** [comment]
> 有时候想按照推送内容关键字搜索，希望增加一个这个功能，改进一下搜索栏，感谢

最新版已支持按内容搜索，点击搜索框左侧的图标即可设置
