### ISSUE TITLE
希望给项目添加图标

### ISSUE THREAD

**Issue by AnxysUaen** [yafoo/pushme#20]
至少App需要一个图标
这里提供几个
![原图](https://github.com/user-attachments/assets/b458abde-4694-469e-88b7-222c26f21f46)

**Comment by AnxysUaen** [comment]
个人喜欢第三张，图片来源为 AI生成 无版权问题

**Comment by yafoo** [comment]
哈哈，app现在还没有一个自己的图标，主要是不会设计，设计太难了。安卓默认图标挺好看的，也同属绿色系，就一直没做图标。

第三个挺好看的，可以把电报图标替换了。
