### ISSUE TITLE
消息通道：支持自定义，方便设置不同的声音、震动、通知方式 该功能未生效

### ISSUE THREAD

**Issue by loveitmac** [yafoo/pushme#21]
小米14u手机安装了2.6的版本，通过电脑端下发了几条测试信息，并未看到消息通道设置。
如图。
![b93471e789aca1a277377c92ba69202](https://github.com/user-attachments/assets/dab6fdc3-1c65-493d-ad51-11133e00fcd6)
![image](https://github.com/user-attachments/assets/c39f2e20-d01c-4798-ba34-4a2ceaed741e)

**Comment by yafoo** [comment]
![Screenshot_2024-10-04-23-18-39-964_com android settings](https://github.com/user-attachments/assets/ff0f62c1-0ac0-4fe7-a5d6-d8ab47ad46ae)

在手机通知设置里进行设置声音…提示，你看下这里有新的通知类别没？

**Comment by yafoo** [comment]
另外你图片里，push_key泄露了，可以在push_key获取那里更新一下

**Comment by loveitmac** [comment]
> ![Screenshot_2024-10-04-23-18-39-964_com android settings](https://private-user-images.githubusercontent.com/28701924/373696430-ff0f62c1-0ac0-4fe7-a5d6-d8ab47ad46ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTc4ODYsIm5iZiI6MTcyODA5NzU4NiwicGF0aCI6Ii8yODcwMTkyNC8zNzM2OTY0MzAtZmYwZjYyYzEtMGFjMC00ZmU3LWE1ZDYtZDhhYjQ3YWQ0NmFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDAzMDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MzNkODc4Y2JlYzQ2OGExYmFhYWUxNjU4MDQ2MDJjODgxNGM5ZjAzMjQ4ODY3OWE0MGJlN2FiMDg1NjgzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7XsbKTzX2SCwdcaujZ_ORKXpl9-Ig89h9ZTv8ND63AM)
> 
> 在手机通知设置里进行设置声音…提示，你看下这里有新的通知类别没？

ok，找到了。
不过有个bug：
震动只有开启后第一次生效，之后的通知都不会生效。
声音是正常的。
谢谢。

**Comment by loveitmac** [comment]
> 另外你图片里，push_key泄露了，可以在push_key获取那里更新一下

感谢提醒

**Comment by yafoo** [comment]
震动只第一次生效：你把通知划拉掉，再发就会又震动了。

本来应用可以自己定义通知方式的，但是现在一般手机系统都把通知接管了，app自定义的效果，还得手机系统里再开启才行。震动一次，也是手机系统把后面的震动优化没了。之前测试过，通知不划拉掉，发的多了，声音提示都没有。

**Comment by loveitmac** [comment]
> 震动只第一次生效：你把通知划拉掉，再发就会又震动了。
> 
> 本来应用可以自己定义通知方式的，但是现在一般手机系统都把通知接管了，app自定义的效果，还得手机系统里再开启才行。震动一次，也是手机系统把后面的震动优化没了。之前测试过，通知不划拉掉，发的多了，声音提示都没有。

多谢解惑。目前满足使用需求，感谢。
