### ISSUE TITLE
能否实现通过手机厂商的官方通道进行推送

### ISSUE THREAD

**Issue by yussuy** [yafoo/pushme#22]
可否实现各品牌手机官方通道进行消息推送，如iOS/FCM/小米/华为/vivo/oppo等，实现无需挂后台利用官方通道进行通知推送。
类似竞品（我理解的），Server酱³正在做的，[Server酱³ App](https://sc3.ft07.com/client)

**Comment by yafoo** [comment]
现在有点困难，官方通道目前都不支持个人申请接入的，只有企业才有资格。
常驻后台，设置上有点麻烦。耗电量还行，可以忽略。
