### ISSUE TITLE
反复接收到最后一条消息

### ISSUE THREAD

**Issue by NateScarlet** [yafoo/pushme#23]
红米K60  APP版本: v2.6.0

用的官方服务器 昨天还好的 今天17:26起就一直提醒最后一条 

消息列表里都是第一条的时间 实际是刚接收的

每次杀进程重开就会收到一条 一直开着也会时不时收到

![2f9c630168dbd2b24821c8339deaf20](https://github.com/user-attachments/assets/36e0c09a-37e7-46b5-844d-c03e7340f919)

**Comment by yafoo** [comment]
zhyaphoo，你加一下我微信吧，排查下问题

**Comment by NateScarlet** [comment]
我降级回 2.3.0 就好了

**Comment by yafoo** [comment]
> 我降级回 2.3.0 就好了

应该不是版本的问题。你的app好像也没保活成功。加一下我微信，看看是怎么回事。

没保活成功，服务会频繁断开连接，次数多了，可能就乱了。
