### ISSUE TITLE
小米HyperOS最新版开了所有权限收到几条推送之后就再也收不到了

### ISSUE THREAD

**Issue by MUskby** [yafoo/pushme#4]
开启了自启动，省电设置为无限制，后台锁定依然不行
切换了key之后会再次收到几条，之后就又收不到推送了

**Comment by yafoo** [comment]
我这边没有小米HyperOS的手机不方便测试，允许自启动、允许后台运行，这两项权限打开了是吧？

你把通道通知打开，看看息屏后，消息通道连接是否断开了？

另外，之前看到一个用户的体验（https://powersee.github.io/2023/10/PushMe/），里面写到MIUI的系统，应用处于前台时，消息通道连接过一会儿会断开，如果从多任务里把APP划掉，反而可以保持消息通道服务后台一直运行，你划掉再试下。

**Comment by MUskby** [comment]
目前整体设置是这样的
![Screenshot_2023-11-17-16-01-11-879_com.android.pushme.jpg](https://github.com/yafoo/pushme/assets/6915737/b9c67792-b4bc-4645-bfe7-3ef16894fe91)

![Screenshot_2023-11-17-16-01-24-262_com.miui.securitycenter.jpg](https://github.com/yafoo/pushme/assets/6915737/620880fd-0a1c-44d8-ad4d-9397e26367be)

![Screenshot_2023-11-17-16-01-35-280_com.android.settings.jpg](https://github.com/yafoo/pushme/assets/6915737/aacdb6b8-cb5c-4fc5-9be3-a810442af90a)

![Screenshot_2023-11-17-16-01-42-935_com.android.settings.jpg](https://github.com/yafoo/pushme/assets/6915737/66e7ad55-ae2b-481a-954a-8f5cde588f31)

那个用户的情况我也看了，刚开始的情况类似，后台锁定和划掉都试了，不一定在什么情况下就收不到通知了，刚切换key之后还是可以息屏收到通知的，但是过一段时间就没有消息了，一度以为是设置问题，但是翻来翻去还是没找到规律，不知道是什么原因。

**Comment by yafoo** [comment]
在手机系统通知设置里，把StateChannel的通知也打开，在第二张截图里，点开“权限管理”，看看后台运行的选项打开没？自启动喝后台运行，是两项分开的权限。

**Comment by kky5** [comment]
都打开了，还是没有用。

**Comment by MUskby** [comment]
> 在手机系统通知设置里，把StateChannel的通知也打开，在第二张截图里，点开“权限管理”，看看后台运行的选项打开没？自启动和后台运行，是两项分开的权限。

后台是在省点策略里面，已经设置了不限制，锁了后台就不会被杀后台了

**Comment by yafoo** [comment]
刚在miui14上测试，确实只有锁定APP，才能保证后台运行，其他方法不好使。HyperOS现在没法测试

**Comment by MUskby** [comment]
不过也很感谢大佬了，期待后续更新能够解决这个问题

**Comment by MUskby** [comment]
问题好像解决了
具体操作如下：
进入应用信息详情页，选择清空应用所有数据，重新获取到key，这时候无论是否自启动是否开启通知，都可以收到推送消息，但是保险起见还是打开自启动，省电策略调整为无限制，通知通道设置为正常，截止目前为止，接收正常。

**Comment by yafoo** [comment]
> 问题好像解决了
> 具体操作如下：
> 进入应用信息详情页，选择清空应用所有数据，重新获取到key，这时候无论是否自启动是否开启通知，都可以收到推送消息，但是保险起见还是打开自启动，省电策略调整为无限制，通知通道设置为正常，截止目前为止，接收正常。

你再观察观察看看，这种情况比较奇怪，之前没遇到过，我也再看看代码逻辑。看现象，有点像key冲突，一个key只能对应一个app，要是应用双开，两个app共用一个key得话，会争夺key掉线。

这次经过测试，miui（14）必须的开启自启动、省电无限制、锁定后台，三项都设置才能保持后台运行，而且这时把app从多任务页面划掉，也能一直后台运行。

另外：

1、这次测试发现通道通知在miui系统上显示有问题（小米乱改安卓通知），显示不全。通道通知只是用来观察是否在线的，不影响后台运行。
2、发现一直存在的一个问题，在手机网络断网或切换时，可能会造成app离线，并且不会自己再连上，需要重启app才行，这个问题复现的概率还挺高的。之前修复过几次，没有真正修复。

目前这两个问题都已修复，主要刚好这周有点忙，预计下周发新版本。

**Comment by MUskby** [comment]
好的，还是感谢🙏

**Comment by MUskby** [comment]
> > 问题好像解决了
> > 具体操作如下：
> > 进入应用信息详情页，选择清空应用所有数据，重新获取到key，这时候无论是否自启动是否开启通知，都可以收到推送消息，但是保险起见还是打开自启动，省电策略调整为无限制，通知通道设置为正常，截止目前为止，接收正常。
> 
> 你再观察观察看看，这种情况比较奇怪，之前没遇到过，我也再看看代码逻辑。看现象，有点像key冲突，一个key只能对应一个app，要是应用双开，两个app共用一个key得话，会争夺key掉线。
> 
> 这次经过测试，miui（14）必须的开启自启动、省电无限制、锁定后台，三项都设置才能保持后台运行，而且这时把app从多任务页面划掉，也能一直后台运行。
> 
> 另外：
> 
> 1、这次测试发现通道通知在miui系统上显示有问题（小米乱改安卓通知），显示不全。通道通知只是用来观察是否在线的，不影响后台运行。
> 2、发现一直存在的一个问题，在手机网络断网或切换时，可能会造成app离线，并且不会自己再连上，需要重启app才行，这个问题复现的概率还挺高的。之前修复过几次，没有真正修复。
> 
> 目前这两个问题都已修复，主要刚好这周有点忙，预计下周发新版本。

好的，还是感谢🙏
