### ISSUE TITLE
重启后不主动打开app就无法收到通知了

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme#5]
这个有解嘛

**Comment by yafoo** [comment]
可能不同的手机限制程度不一样。我的vivo x50 安卓13，自启动那些权限设置后，重启手机，pushme后台服务是会自动启动的。你的什么手机？安卓哪个版本？

**Comment by liesauer** [comment]
一加9rt，ColorOS 12.1，Andorid 12

**Comment by liesauer** [comment]
我后来又测试了一下，我第一次重启前是先在任务列表手动划掉再重启的，我以为是这个影响了，但是我不划掉直接重启，也是收不到。

有什么办法能确认服务有没有开起来吗？设置里面或者adb命令，啥都行。

**Comment by liesauer** [comment]
更新：我第二次测试完后，在设置的开发者选项里面查到是没有pushme的服务的，但是我划着划着突然就发现多了pushme的服务了，通知也出来了，此时大概是重启后3分钟左右，会不会是系统的延迟启动优化？不太懂安卓的机制，不确定会不会有这种操作

**Comment by liesauer** [comment]
我刚刚又测试了几回，看起来确实是延迟启动之类的机制在作怪，测试三回，不管重启前有没有划掉前台，重启后都是大概在3-5分钟后才启动pushme的服务

**Comment by yafoo** [comment]
> 我后来又测试了一下，我第一次重启前是先在任务列表手动划掉再重启的，我以为是这个影响了，但是我不划掉直接重启，也是收不到。
> 
> 有什么办法能确认服务有没有开起来吗？设置里面或者adb命令，啥都行。

在通知设置里，把state channel通知也打开，这个通道是专门常驻通知栏显示服务状态的，你试试。

**Comment by liesauer** [comment]
> > 我后来又测试了一下，我第一次重启前是先在任务列表手动划掉再重启的，我以为是这个影响了，但是我不划掉直接重启，也是收不到。
> > 有什么办法能确认服务有没有开起来吗？设置里面或者adb命令，啥都行。
> 
> 在通知设置里，把state channel通知也打开，这个通道是专门常驻通知栏显示服务状态的，你试试。

disconnected是怎么判断的，因为我一开始下载app测试的时候，前一秒还是connected，转眼就变disconnected了，前后台都有的情况下，自启、电池优化都弄了，留在了桌面几分钟，当时在测试通知栏的显示效果，反正怪怪的，我就关了这个通知。

**Comment by yafoo** [comment]
> > > 我后来又测试了一下，我第一次重启前是先在任务列表手动划掉再重启的，我以为是这个影响了，但是我不划掉直接重启，也是收不到。
> > > 有什么办法能确认服务有没有开起来吗？设置里面或者adb命令，啥都行。
> > 
> > 
> > 在通知设置里，把state channel通知也打开，这个通道是专门常驻通知栏显示服务状态的，你试试。
> 
> disconnected是怎么判断的，因为我一开始下载app测试的时候，前一秒还是connected，转眼就变disconnected了，前后台都有的情况下，自启、电池优化都弄了，留在了桌面几分钟，当时在测试通知栏的显示效果，反正怪怪的，我就关了这个通知。

现在还有disconnected的情况没？通过服务端确实观察到有些客户端一直在反复连接再断开，暂时我也不知道原因，我手机没这情况，没法调试。

**Comment by liesauer** [comment]
现在暂时没发现

**Comment by yafoo** [comment]
> 现在暂时没发现

那应该就是没事了，可能那会儿网络不稳定吧
