### ISSUE TITLE
数据小屏排序问题

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme#6]
经测试，新推送的会往前显示，接口可以添加排序字段用于显示排序嘛

排序越小则越往前显示，相同排序的就保持原有的按推送时间排序

这样子就能做到类似于置顶的功能，并能随意调整重要等级，不会因为发送新通知导致全都乱套了

重要A -999   重要B -998
其他C 默认0  其他D 默认0

**Comment by yafoo** [comment]
嗯，为了表达数据更新了，所以设计时默认按更新时间倒序来排了。
后面我加个设置排序的功能。

**Comment by yafoo** [comment]
最新版，已增加数据小屏排序功能
