### ISSUE TITLE
开源自部署

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme#7]
请问是否以后有开源以及自部署的打算，亦或是收费计划。

1. 随着以后越来越多用户使用，在不收费的前提下，仅靠官方服务器也会存在很大的压力
2. 会推送一些较敏感的数据，不想被人知道
3. 数据小屏对我来是挺有用的，可能会推送的很频繁，一分钟推十几二十个通知，不管以后的免费限量推送或者是收费计划对我都会有比较大的影响。

**Comment by yafoo** [comment]
嗯，这三个问题我都有考虑过：
1. 我的服务扛不住的时候，会提供自建服务。
2. 我还在想除了加密之外更好的解决方案。
3. 数据小屏是独有的设计，也是我自己有这个需求。不过确实存在推送频繁的问题，这个后续开发时一步一步解决。

**Comment by liesauer** [comment]
好的，感谢回复
