### ISSUE TITLE
卡片消息通知

### ISSUE THREAD

**Issue by liesauer** [yafoo/pushme#8]
希望能添加类似于微信公众号里的那种卡片消息

1. 有比较固定的标题正文布局，支持图文
2. 可以有交互按钮，并发送回调

**Comment by yafoo** [comment]
卡片消息这个需求，估计短时间不会做
1. pushme支持markdown格式消息，可以实现图文需求
2. 回调其实就是个url请求，可以在markdown消息最后加个超链接，然后点击链接，会自动浏览器打开，以实现请求。

目前api接口，除了token，有4个字段，最少只用传一个字段就行了。不想把字段搞得太复杂。
