### ISSUE TITLE
澎湃OS更新了1.10.0版本后闪退

### ISSUE THREAD

**Issue by MUskby** [yafoo/pushme#9]
即使是清除所有数据依旧闪退，直接无法启动

**Comment by yafoo** [comment]
在APP权限设置那里，对应本APP的权限，看看有没有alarm闹钟之类的权限，有的话，打开权限试试，另外我在android14上再调试下看看。

**Comment by yafoo** [comment]
尴尬了，确实安卓14兼容问题，一会儿我修复后再发一个版本

**Comment by yafoo** [comment]
> 即使是清除所有数据依旧闪退，直接无法启动

已发布最新版v1.10.1，你下载试试

**Comment by MUskby** [comment]
已修复，使用正常，感谢大佬。
